# Generated by Django 5.0.1 on 2024-02-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imuser",
            name="groups",
            field=models.ManyToManyField(related_name="imuser_set", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="imuser",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="imuser_set", to="auth.permission"
            ),
        ),
    ]
