# Generated by Django 5.0.1 on 2024-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_usertype_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertype",
            name="name",
        ),
        migrations.AddField(
            model_name="usertype",
            name="type_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
