# Generated by Django 5.0.1 on 2024-02-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_imuser_groups_alter_imuser_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("EIT", "Engineering Intern"),
                    ("TEACHING_FELLOW", "Teaching Fellow"),
                    ("ADMIN_STAFF", "Administrative Staff"),
                    ("ADMIN", "Administrator"),
                ],
                default="EIT",
                max_length=20,
            ),
        ),
    ]
