# Generated by Django 5.0.1 on 2024-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_imuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="imuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="imuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
