# Generated by Django 5.0.1 on 2024-02-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_usertype_name_usertype_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IMUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usertype"
                    ),
                ),
            ],
        ),
    ]
