# Generated by Django 5.0.1 on 2024-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_imuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
