# Generated by Django 5.0.1 on 2024-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_course_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_date_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
