# Generated by Django 5.0.1 on 2024-02-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_querycomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querycomment",
            name="comment",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
